# Generated by Django 6.0.6 on 2026-06-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa matn')),
                ('button_text', models.CharField(blank=True, max_length=80, null=True, verbose_name='Tugma matni')),
                ('button_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Havola')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi")),
            ],
            options={
                'verbose_name': 'Kontakt xabari',
                'verbose_name_plural': 'Kontakt xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Kupon kodi')),
                ('discount_type', models.CharField(choices=[('percent', 'Foiz'), ('amount', "So'm")], default='percent', max_length=20, verbose_name='Chegirma turi')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chegirma qiymati')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimal buyurtma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kuponlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False, verbose_name='Javob berilganmi')),
            ],
            options={
                'verbose_name': 'Chat support xabari',
                'verbose_name_plural': 'Chat support xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chegirma'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Tuman/Shahar'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='SKU kodi'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='Xususiyatlar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('uzcard', 'Uzcard'), ('humo', 'Humo'), ('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme'), ('uzumbank', 'Uzum Bank')], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('processing', 'Tasdiqlandi'), ('shipped', 'Yuborildi'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.coupon', verbose_name='Kupon'),
        ),
    ]
